package com.kbo.form.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Componente generated by hbm2java
 */
public class Componente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer comId;
	private Integer secId;
	private int comTipo;
	private String comDesc;
	private String comOrden;
	private String comBinding;
	private char comRequerido;
	private String comCatalogo;
	private String comEnablePer;
	private String comVisiblePer;
	private Integer comPosicion;
	private Set grupoComponentesForComId = new HashSet(0);

	public Componente() {
	}

	public Integer getComId() {
		return this.comId;
	}

	public void setComId(Integer comId) {
		this.comId = comId;
	}

	/**
	 * @return the secId
	 */
	public Integer getSecId() {
		return secId;
	}

	/**
	 * @param secId the secId to set
	 */
	public void setSecId(Integer secId) {
		this.secId = secId;
	}

	public int getComTipo() {
		return this.comTipo;
	}

	public void setComTipo(int comTipo) {
		this.comTipo = comTipo;
	}

	public String getComDesc() {
		return this.comDesc;
	}

	public void setComDesc(String comDesc) {
		this.comDesc = comDesc;
	}

	public String getComOrden() {
		return this.comOrden;
	}

	public void setComOrden(String comOrden) {
		this.comOrden = comOrden;
	}

	public String getComBinding() {
		return this.comBinding;
	}

	public void setComBinding(String comBinding) {
		this.comBinding = comBinding;
	}

	public char getComRequerido() {
		return this.comRequerido;
	}

	public void setComRequerido(char comRequerido) {
		this.comRequerido = comRequerido;
	}

	public String getComCatalogo() {
		return this.comCatalogo;
	}

	public void setComCatalogo(String comCatalogo) {
		this.comCatalogo = comCatalogo;
	}

	public String getComEnablePer() {
		return this.comEnablePer;
	}

	public void setComEnablePer(String comEnablePer) {
		this.comEnablePer = comEnablePer;
	}

	public String getComVisiblePer() {
		return this.comVisiblePer;
	}

	public void setComVisiblePer(String comVisiblePer) {
		this.comVisiblePer = comVisiblePer;
	}

	public Integer getComPosicion() {
		return this.comPosicion;
	}

	public void setComPosicion(Integer comPosicion) {
		this.comPosicion = comPosicion;
	}

	public Set getGrupoComponentesForComId() {
		return this.grupoComponentesForComId;
	}

	public void setGrupoComponentesForComId(Set grupoComponentesForComId) {
		this.grupoComponentesForComId = grupoComponentesForComId;
	}

}
