package com.kbo.form.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

/**
 * GrupoComponente generated by hbm2java
 */
public class GrupoComponente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private GrupoComponenteId id;
	private Componente componenteByComId;
	private Componente componenteByGrpComId;

	public GrupoComponente() {
	}

	public GrupoComponente(GrupoComponenteId id, Componente componenteByComId, Componente componenteByGrpComId) {
		this.id = id;
		this.componenteByComId = componenteByComId;
		this.componenteByGrpComId = componenteByGrpComId;
	}

	public GrupoComponenteId getId() {
		return this.id;
	}

	public void setId(GrupoComponenteId id) {
		this.id = id;
	}

	public Componente getComponenteByComId() {
		return this.componenteByComId;
	}

	public void setComponenteByComId(Componente componenteByComId) {
		this.componenteByComId = componenteByComId;
	}

	public Componente getComponenteByGrpComId() {
		return this.componenteByGrpComId;
	}

	public void setComponenteByGrpComId(Componente componenteByGrpComId) {
		this.componenteByGrpComId = componenteByGrpComId;
	}

}
