package com.kbo.form.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

/**
 * GrupoComponenteId generated by hbm2java
 */
public class GrupoComponenteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int comId;
	private int grpComId;
	private String grpCondicion;

	public GrupoComponenteId() {
	}

	public GrupoComponenteId(int comId, int grpComId) {
		this.comId = comId;
		this.grpComId = grpComId;
	}

	public GrupoComponenteId(int comId, int grpComId, String grpCondicion) {
		this.comId = comId;
		this.grpComId = grpComId;
		this.grpCondicion = grpCondicion;
	}

	public int getComId() {
		return this.comId;
	}

	public void setComId(int comId) {
		this.comId = comId;
	}

	public int getGrpComId() {
		return this.grpComId;
	}

	public void setGrpComId(int grpComId) {
		this.grpComId = grpComId;
	}

	public String getGrpCondicion() {
		return this.grpCondicion;
	}

	public void setGrpCondicion(String grpCondicion) {
		this.grpCondicion = grpCondicion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrupoComponenteId))
			return false;
		GrupoComponenteId castOther = (GrupoComponenteId) other;

		return (this.getComId() == castOther.getComId()) && (this.getGrpComId() == castOther.getGrpComId())
				&& ((this.getGrpCondicion() == castOther.getGrpCondicion())
						|| (this.getGrpCondicion() != null && castOther.getGrpCondicion() != null
								&& this.getGrpCondicion().equals(castOther.getGrpCondicion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getComId();
		result = 37 * result + this.getGrpComId();
		result = 37 * result + (getGrpCondicion() == null ? 0 : this.getGrpCondicion().hashCode());
		return result;
	}

}
