package com.kbo.form.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer secId;
	private Integer scfId;
	private int secOrden;
	private String secDesc;
	private Set componentes = new HashSet(0);

	public Seccion() {
	}

	public Integer getSecId() {
		return this.secId;
	}

	public void setSecId(Integer secId) {
		this.secId = secId;
	}

	/**
	 * @return the scfId
	 */
	public Integer getScfId() {
		return scfId;
	}

	/**
	 * @param scfId the scfId to set
	 */
	public void setScfId(Integer scfId) {
		this.scfId = scfId;
	}

	public int getSecOrden() {
		return this.secOrden;
	}

	public void setSecOrden(int secOrden) {
		this.secOrden = secOrden;
	}

	public String getSecDesc() {
		return this.secDesc;
	}

	public void setSecDesc(String secDesc) {
		this.secDesc = secDesc;
	}

	public Set getComponentes() {
		return this.componentes;
	}

	public void setComponentes(Set componentes) {
		this.componentes = componentes;
	}

}
