package com.kbo.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Colonia generated by hbm2java
 */
public class Colonia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer colId;
	private Municipio municipio;
	private String colNom;
	private String colCp;

	public Colonia() {
	}

	public Colonia(Municipio municipio) {
		this.municipio = municipio;
	}

	public Colonia(Municipio municipio, String colNom, String colCp, Set direccions) {
		this.municipio = municipio;
		this.colNom = colNom;
		this.colCp = colCp;
	}

	public Integer getColId() {
		return this.colId;
	}

	public void setColId(Integer colId) {
		this.colId = colId;
	}

	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	public String getColNom() {
		return this.colNom;
	}

	public void setColNom(String colNom) {
		this.colNom = colNom;
	}

	public String getColCp() {
		return this.colCp;
	}

	public void setColCp(String colCp) {
		this.colCp = colCp;
	}

}
