package com.kbo.model;// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dirId;
	private Persona persona;
	private Colonia colonia;
	private String dirMun;
	private String dirCalle;
	private String dirNoext;
	private String dirNoint;

	public Direccion() {
	}

	public Direccion(Persona persona) {
		this.persona = persona;
	}

	public Direccion(Persona persona, Colonia colonia, String dirMun, String dirCalle, String dirNoext,
			String dirNoint) {
		this.persona = persona;
		this.colonia = colonia;
		this.dirMun = dirMun;
		this.dirCalle = dirCalle;
		this.dirNoext = dirNoext;
		this.dirNoint = dirNoint;
	}

	public Integer getDirId() {
		return this.dirId;
	}

	public void setDirId(Integer dirId) {
		this.dirId = dirId;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Colonia getColonia() {
		return this.colonia;
	}

	public void setColonia(Colonia colonia) {
		this.colonia = colonia;
	}

	public String getDirMun() {
		return this.dirMun;
	}

	public void setDirMun(String dirMun) {
		this.dirMun = dirMun;
	}

	public String getDirCalle() {
		return this.dirCalle;
	}

	public void setDirCalle(String dirCalle) {
		this.dirCalle = dirCalle;
	}

	public String getDirNoext() {
		return this.dirNoext;
	}

	public void setDirNoext(String dirNoext) {
		this.dirNoext = dirNoext;
	}

	public String getDirNoint() {
		return this.dirNoint;
	}

	public void setDirNoint(String dirNoint) {
		this.dirNoint = dirNoint;
	}

}
