package com.kbo.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

/**
 * ExpClinico generated by hbm2java
 */
public class ExpClinico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer expId;
	private Integer perId;
	private String expClinicocol;

	public ExpClinico() {
	}

	public Integer getExpId() {
		return this.expId;
	}

	public void setExpId(Integer expId) {
		this.expId = expId;
	}

	/**
	 * @return the perId
	 */
	public Integer getPerId() {
		return perId;
	}

	/**
	 * @param perId the perId to set
	 */
	public void setPerId(Integer perId) {
		this.perId = perId;
	}

	public String getExpClinicocol() {
		return this.expClinicocol;
	}

	public void setExpClinicocol(String expClinicocol) {
		this.expClinicocol = expClinicocol;
	}

}
