package com.kbo.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer perId;
	private String perNombre;
	private String perAppaterno;
	private String perApmaterno;
	private String perEmail;
	private Date perFalta;
	private Set usuarios = new HashSet(0);
	private Set direccions = new HashSet(0);
	private Set expClinicos = new HashSet(0);
	private Set docDats = new HashSet(0);

	public Persona() {
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Persona [perId=" + perId + ", perNombre=" + perNombre + ", perAppaterno=" + perAppaterno
				+ ", perFalta=" + perFalta;
	}

	public Persona(String perNombre, String perAppaterno, Date perFalta) {
		this.perNombre = perNombre;
		this.perAppaterno = perAppaterno;
		this.perFalta = perFalta;
	}

	public Persona(String perNombre, String perAppaterno, String perApmaterno, String perEmail, Date perFalta,
			Set usuarios, Set direccions, Set expClinicos, Set docDats) {
		this.perNombre = perNombre;
		this.perAppaterno = perAppaterno;
		this.perApmaterno = perApmaterno;
		this.perEmail = perEmail;
		this.perFalta = perFalta;
		this.usuarios = usuarios;
		this.direccions = direccions;
		this.expClinicos = expClinicos;
		this.docDats = docDats;
	}

	public Integer getPerId() {
		return this.perId;
	}

	public void setPerId(Integer perId) {
		this.perId = perId;
	}

	public String getPerNombre() {
		return this.perNombre;
	}

	public void setPerNombre(String perNombre) {
		this.perNombre = perNombre;
	}

	public String getPerAppaterno() {
		return this.perAppaterno;
	}

	public void setPerAppaterno(String perAppaterno) {
		this.perAppaterno = perAppaterno;
	}

	public String getPerApmaterno() {
		return this.perApmaterno;
	}

	public void setPerApmaterno(String perApmaterno) {
		this.perApmaterno = perApmaterno;
	}

	public String getPerEmail() {
		return this.perEmail;
	}

	public void setPerEmail(String perEmail) {
		this.perEmail = perEmail;
	}

	public Date getPerFalta() {
		return this.perFalta;
	}

	public void setPerFalta(Date perFalta) {
		this.perFalta = perFalta;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set direccions) {
		this.direccions = direccions;
	}

	public Set getExpClinicos() {
		return this.expClinicos;
	}

	public void setExpClinicos(Set expClinicos) {
		this.expClinicos = expClinicos;
	}

	public Set getDocDats() {
		return this.docDats;
	}

	public void setDocDats(Set docDats) {
		this.docDats = docDats;
	}

}
