package com.kbo.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer usuId;
	private Integer perId;
	private String usuUsuario;
	private String usuPassword;
	private Character usuEstatus;
	private Set usuGrupos = new HashSet(0);

	public Usuario() {
	}


	public Integer getUsuId() {
		return this.usuId;
	}

	public void setUsuId(Integer usuId) {
		this.usuId = usuId;
	}

	/**
	 * @return the perId
	 */
	public Integer getPerId() {
		return perId;
	}

	/**
	 * @param perId the perId to set
	 */
	public void setPerId(Integer perId) {
		this.perId = perId;
	}

	public String getUsuUsuario() {
		return this.usuUsuario;
	}

	public void setUsuUsuario(String usuUsuario) {
		this.usuUsuario = usuUsuario;
	}

	public String getUsuPassword() {
		return this.usuPassword;
	}

	public void setUsuPassword(String usuPassword) {
		this.usuPassword = usuPassword;
	}

	public Character getUsuEstatus() {
		return this.usuEstatus;
	}

	public void setUsuEstatus(Character usuEstatus) {
		this.usuEstatus = usuEstatus;
	}

	public Set getUsuGrupos() {
		return this.usuGrupos;
	}

	public void setUsuGrupos(Set usuGrupos) {
		this.usuGrupos = usuGrupos;
	}

}
