package com.kbo.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

/**
 * UsuGrupo generated by hbm2java
 */
public class UsuGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsuGrupoId id;
	private Usuario usuario;
	private Grupo grupo;

	public UsuGrupo() {
	}

	public UsuGrupo(UsuGrupoId id, Usuario usuario, Grupo grupo) {
		this.id = id;
		this.usuario = usuario;
		this.grupo = grupo;
	}

	public UsuGrupoId getId() {
		return this.id;
	}

	public void setId(UsuGrupoId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

}
