package com.kbo.model;
// Generated 23/04/2017 04:07:46 PM by Hibernate Tools 4.0.0.Final

/**
 * UsuGrupoId generated by hbm2java
 */
public class UsuGrupoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int usuId;
	private int grpId;

	public UsuGrupoId() {
	}

	public UsuGrupoId(int usuId, int grpId) {
		this.usuId = usuId;
		this.grpId = grpId;
	}

	public int getUsuId() {
		return this.usuId;
	}

	public void setUsuId(int usuId) {
		this.usuId = usuId;
	}

	public int getGrpId() {
		return this.grpId;
	}

	public void setGrpId(int grpId) {
		this.grpId = grpId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuGrupoId))
			return false;
		UsuGrupoId castOther = (UsuGrupoId) other;

		return (this.getUsuId() == castOther.getUsuId()) && (this.getGrpId() == castOther.getGrpId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsuId();
		result = 37 * result + this.getGrpId();
		return result;
	}

}
